name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/eratemanager

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Go test
        run: go test ./...

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Install helm-unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run helm unittest
        working-directory: ./helm/eratemanager
        run: |
          helm unittest .

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  kind-smoke:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.0

      - name: Install kind
        uses: helm/kind-action@v1.9.0
        with:
          version: v0.23.0

      - name: Create kind cluster
        run: |
          kind create cluster --name eratemanager-ci

      - name: Load image from GHCR into kind
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          kind load docker-image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --name eratemanager-ci

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Deploy chart to kind
        run: |
          helm upgrade --install eratemanager ./helm/eratemanager                 --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}                 --set image.tag=${{ github.sha }}

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/eratemanager --timeout=120s

      - name: Check /healthz via port-forward
        run: |
          kubectl port-forward svc/eratemanager 18080:80 &
          PF_PID=$!
          sleep 5
          curl -f http://127.0.0.1:18080/healthz
          kill $PF_PID
